[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
license = ""


[workspace.dependencies]
anyhow = "~1"
rand = "~0.8"

# Local crates

## dev-dependencies
divan = "~0.1"
