[package]
name = "crypto"
version = "0.1.0"
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
rand.workspace = true

# Local crates

[dev-dependencies]
divan.workspace.dev-dependencies = true

[[bench]]
name = "sieve"
harness = false
